### ISSUE TITLE
Plans for julia 1.0?

### ISSUE THREAD

**Issue by phaverty** [BioJulia/GenomicFeatures.jl#14]
Are there plans to get GenomicFeatures ready for julia 1.0? How can I help?

**Comment by BenJWard** [comment]
Hey @phaverty, there's a branch (creatively) called "updates", which has a few commits ahead of master already, including appveyor and travis changes to julia v0.7 / v1.0. This updates branch has an associated PR here: https://github.com/BioJulia/GenomicFeatures.jl/pull/15. The plan is to apply changes until everything builds and tests fine. You can either apply changes directly to the "updates" branch if you like, or use it as a base for your own PRs.

**Comment by BenJWard** [comment]
It might be better to PR against "updates" just incase any squashes of commits and the like involving force pushes occurs.

**Comment by phaverty** [comment]
Excellent, thanks. I'll set aside some evening coding time to see what I
can do.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by BenJWard** [comment]
Awesome :)

Also I’ve just noticed that before GenomicFeatures can be upgraded, we need to have a 0.7/1.0 release for BGZFStreams first as it’s a dependency, so there’s a want for updates contributions there as well :)

**Comment by phaverty** [comment]
I saw that BioSequences released their version for 1.0. BGZFStreams looks
like it is ready to go.  I don't really know anything about the compression
domain, but if it's just modernizing syntax, I can help.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by BenJWard** [comment]
@phaverty So it does! The errors I saw must have been due to the non 1.0 version of BGZFStreams being used.

**Comment by BenJWard** [comment]
@phaverty The next release should fix this as a result of the two PRs Dan and myself done did. When it goes through to METADATA I'll close this.

**Comment by phaverty** [comment]
Fantastic! Sorry I wasn't more help. I'll keep an eye out for a place to contribute in the future.
