### ISSUE TITLE
Deprecated expressions in documents

### ISSUE THREAD

**Issue by yuifu** [BioJulia/GenomicFeatures.jl#17]
Thank you for developing nice package.

In `docs/src/intervals.md`, I found `Void`, which should be replaced with `Nothing`.

**Comment by CiaranOMara** [comment]
Commit https://github.com/BioJulia/GenomicFeatures.jl/commit/85b9fe0c74e8f71abfdefc4687b980ce3415813c#diff-3be040248bfbf1b94fe20d9a98837edfL94-R95 will address this issue in an upcoming release.
